server : server.o Linked_List.o message_type.o
	cc message_type.o server.o Linked_List.o -o server -Wall -O0
Linked_List.o : Linked_List.h Linked_List.c 
message_type.o : message_type.h
server.o : server.c Linked_List.h


